apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    metadata:
      name: example-pod
    spec:
      containers:
      - name: example-container
        image: busybox:1.34
        command: ["echo", "Hello, Kubernetes!"]
      restartPolicy: Never

